---
# Create or update a template deployment based on uris using parameter and template links

- hosts: localhost
  
  tasks:
  - name: create an account
    azure_rm_storageaccount:
      resource_group: AZUREDEVOPSDEMO
      template_link: 'https://github.com/sudheer5561/AzureRMdeploy/blob/main/azuredeploy.json'
      parameters_link: 'https://github.com/sudheer5561/AzureRMdeploy/blob/main/azuredeploy.parameters.json'

...