---
# Create or update a template deployment based on uris using parameter and template links

- name: Create Azure Gallery
  hosts: localhost
  connection: local

  azure_rm_deployment:
    resource_group: AZUREDEVOPSDEMO
    name: VMDeployment
    template_link: 'https://github.com/sudheer5561/AzureRMdeploy/blob/main/ImageGallery-template.json'
    parameters_link: 'https://github.com/sudheer5561/AzureRMdeploy/blob/main/ImageGallery-parameters.json'

...