---
# Create or update a template deployment based on uris using parameter and template links

- hosts: localhost
  
  tasks:
  - name: Creation VM
    azure_rm_deployment:
      resource_group: AZUREDEVOPSDEMO2
      location: France Central
      template_link: 'https://raw.githubusercontent.com/sudheer5561/AzureRMdeploy/blob/main/azuredeploy.json'
      parameters_link: 'https://raw.githubusercontent.com/sudheer5561/AzureRMdeploy/blob/main/azuredeploy.parameters.json'

...